"""Docker Compose file generation and orchestration"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_compose.ipynb.

# %% auto #0
__all__ = ['SWAG_MODS', 'dict2str', 'service', 'DockerCompose', 'Compose', 'swag_conf', 'swag', 'appfile']

# %% ../nbs/01_compose.ipynb #5c7c6242
import yaml
from functools import partial
from fastcore.all import Path, L, merge, listify, filter_values
from .core import Dockerfile, calldocker, _CLI, _build_flags

# %% ../nbs/01_compose.ipynb #59e66642
def dict2str(d:dict, sep=':'): return [f'{k}{sep}{v}' for k,v in d.items()] if isinstance(d, dict) else d
def service(image=None, build=None, ports=None, env=None, volumes=None, depends_on=None, command=None, **kw):
    'Create a docker-compose service dict'
    if isinstance(build, Dockerfile): build = '.'
    return filter_values(dict(image=image, command=command, depends_on=depends_on,
        ports=dict2str(ports), build=build, environment=dict2str(env,'='),
        volumes=dict2str(volumes)), lambda v: v is not None) | kw

# %% ../nbs/01_compose.ipynb #99vr212jmdr
class DockerCompose(_CLI):
    'Wrap docker compose CLI: __getattr__ dispatches subcommands, kwargs become flags'
    def __init__(self, path='docker-compose.yml'): self.path = path
    def _run(self, cmd, *args): return calldocker('compose', '-f', self.path, cmd, *args)

# %% ../nbs/01_compose.ipynb #37a115b0
class Compose(L):
    'Fluent builder for docker-compose.yml files'
    def _add(self, item): return self._new(self.items + [item])
    def svc(self, name, **kw): return self._add(('svc', name, service(**kw)))
    def network(self, name, **kw): return self._add(('net', name, kw or None))
    def volume(self, name, **kw): return self._add(('vol', name, kw or None))

    @classmethod
    def load(cls, path='docker-compose.yml'):
        'Load an existing docker-compose.yml'
        d = yaml.safe_load(Path(path).read_text())
        it = [('svc', n, c) for n, c in (d.get('services') or {}).items()]
        it += [('net', n, c) for n, c in (d.get('networks') or {}).items()]
        it += [('vol', n, c) for n, c in (d.get('volumes') or {}).items()]
        return cls(it)

    def to_dict(self):
        'Render full compose config as dict'
        d = {'services': {n: c for t, n, c in self if t == 'svc'}}
        nets = {n: c for t, n, c in self if t == 'net'}
        vols = {n: c for t, n, c in self if t == 'vol'}
        if nets: d['networks'] = nets
        if vols: d['volumes'] = vols
        return d

    def __str__(self):  return yaml.dump(self.to_dict(), default_flow_style=False, sort_keys=False)
    def __repr__(self): return str(self)
    def save(self, path='docker-compose.yml'): Path(path).write_text(str(self))

    def up(self, detach=True, path='docker-compose.yml', **kw):
        'Run docker compose up'
        self.save(path); return DockerCompose(path).up(d=detach, **kw)

    def down(self, path='docker-compose.yml', **kw):
        'Run docker compose down'
        self.save(path); return DockerCompose(path).down(**kw)

# %% ../nbs/01_compose.ipynb #654a46a9e3e44be8
SWAG_MODS = {
    'auto-proxy':         'linuxserver/mods:swag-auto-proxy',
    'docker':             'linuxserver/mods:universal-docker',
    'cloudflare-real-ip': 'linuxserver/mods:swag-cloudflare-real-ip',
    'crowdsec':           'linuxserver/mods:swag-crowdsec',
    'dashboard':          'linuxserver/mods:swag-dashboard',
    'auto-reload':        'linuxserver/mods:swag-auto-reload',
    'maxmind':            'linuxserver/mods:swag-maxmind',
    'dbip':               'linuxserver/mods:swag-dbip',
}

# %% ../nbs/01_compose.ipynb #7490d68ea0e0442b
def swag_conf(domain, port, app='app'):
    'SWAG nginx site-conf for reverse-proxying to app'
    return (f'server {{\n    listen 443 ssl;\n    server_name {domain};\n'
            f'    include /config/nginx/ssl.conf;\n    location / {{\n'
            f'        proxy_pass http://{app}:{port};\n        include /config/nginx/proxy.conf;\n    }}\n}}\n')

# %% ../nbs/01_compose.ipynb #7d269b1de0554327
def swag(domain, app='app', port=None, conf_path='proxy.conf',
         validation='http', subdomains='wildcard',
         cloudflared=False, mods=None, **kw):
    'SWAG reverse-proxy service kwargs for Compose.svc()'
    if port: Path(conf_path).mk_write(swag_conf(domain, port, app))
    env = merge({'PUID': '1000', 'PGID': '1000', 'TZ': 'Etc/UTC',
                 'URL': domain, 'SUBDOMAINS': subdomains, 'VALIDATION': validation}, kw)
    mod_tags = [SWAG_MODS[m] for m in listify(mods) if m in SWAG_MODS]
    if cloudflared:
        mod_tags.append('linuxserver/mods:universal-cloudflared')
        env['CF_REMOTE_MANAGE_TOKEN'] = '${CF_TUNNEL_TOKEN}'
    if mod_tags: env['DOCKER_MODS'] = '|'.join(mod_tags)
    r = dict(image='lscr.io/linuxserver/swag', env=env,
        volumes={'swag_config': '/config', './proxy.conf': '/config/nginx/site-confs/proxy.conf'},
        networks=['web'], depends_on=[app], cap_add=['NET_ADMIN'], restart='unless-stopped')
    if not cloudflared: r['ports'] = {443: 443, 80: 80}
    return r

# %% ../nbs/01_compose.ipynb #739c5d1df22a4c39
def appfile(port=5001, volume='/app/data', image='python:3.12-slim'):
    'Standard Python webapp Dockerfile'
    df = Dockerfile().from_(image).workdir('/app').copy('requirements.txt', '.').run('pip install --no-cache-dir -r requirements.txt').copy('.', '.')
    if volume: df = df.run(f'mkdir -p {volume}')
    return df.expose(port).cmd(['python', 'main.py'])
