"""Framework-specific Dockerfile generators for common web app patterns"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_apps.ipynb.

# %% auto #0
__all__ = ['python_app', 'fasthtml_app', 'fastapi_react', 'go_app', 'rust_app']

# %% ../nbs/05_apps.ipynb #94ce90e3
from fastcore.all import listify
from .core import Dockerfile

# %% ../nbs/05_apps.ipynb #73f5549a
def python_app(port=8000, cmd=None, image='python:3.12-slim', workdir='/app',
               pkgs=None, volumes=None, uv=True, healthcheck=None):
    'Single-stage Python app Dockerfile. uv=True (default) uses uv for fast installs.'
    df = Dockerfile().from_(image).workdir(workdir)
    if pkgs:
        df = df.apt_install(*listify(pkgs), y=True).run('rm -rf /var/lib/apt/lists/*')
    if uv:
        df = (df.copy('/uv', '/usr/local/bin/uv', from_='ghcr.io/astral-sh/uv:latest')
                .copy('pyproject.toml', '.').copy('uv.lock', '.')
                .run_mount('uv sync --frozen --no-dev', target='/root/.cache/uv'))
    else:
        df = df.copy('requirements.txt', '.').run('pip install --no-cache-dir -r requirements.txt')
    df = df.copy('.', '.')
    for v in listify(volumes or []):
        df = df.run(f'mkdir -p {v}')
    if healthcheck:
        df = df.healthcheck(f'curl -f http://localhost:{port}{healthcheck}', i='30s', t='5s', r='3')
    df = df.expose(port)
    _cmd = cmd or ['python', 'main.py']
    return df.cmd(_cmd if isinstance(_cmd, list) else _cmd.split())

# %% ../nbs/05_apps.ipynb #1dcf1d9f
def fasthtml_app(port=5001, cmd=None, image='python:3.12-slim', pkgs=None,
                 volumes=None, healthcheck=None):
    'FastHTML/FastAPI single-stage Dockerfile with uv'
    return python_app(port=port, cmd=cmd, image=image, pkgs=pkgs,
                      volumes=volumes, uv=True, healthcheck=healthcheck)

# %% ../nbs/05_apps.ipynb #9421df12
def fastapi_react(port=8000, node_version='20', frontend_dir='frontend', build_dir='dist',
                  image='python:3.12-slim', pkgs=None, uv=True, healthcheck='/health'):
    'Two-stage Dockerfile: Node.js frontend build + Python/FastAPI backend'
    df = (Dockerfile()
        .from_(f'node:{node_version}-slim', as_='frontend')
        .workdir('/build')
        .copy(f'{frontend_dir}/package*.json', '.')
        .run('npm ci')
        .copy(frontend_dir, '.')
        .run('npm run build')
        .from_(image).workdir('/app'))
    if pkgs:
        df = df.apt_install(*listify(pkgs), y=True).run('rm -rf /var/lib/apt/lists/*')
    if uv:
        df = (df.copy('/uv', '/usr/local/bin/uv', from_='ghcr.io/astral-sh/uv:latest')
                .copy('pyproject.toml', '.').copy('uv.lock', '.')
                .run_mount('uv sync --frozen --no-dev', target='/root/.cache/uv'))
    else:
        df = df.copy('requirements.txt', '.').run('pip install --no-cache-dir -r requirements.txt')
    df = (df.copy('.', '.')
            .copy(f'/build/{build_dir}', '/app/static', from_='frontend'))
    if healthcheck:
        df = df.healthcheck(f'curl -f http://localhost:{port}{healthcheck}', i='30s', t='5s', r='3')
    return df.expose(port).cmd(['uvicorn', 'main:app', '--host', '0.0.0.0', f'--port={port}'])

# %% ../nbs/05_apps.ipynb #bf7ff23c
def go_app(port=8080, go_version='1.22', binary='app', runtime='gcr.io/distroless/static',
           cmd=None, cgo=False):
    'Two-stage Go Dockerfile: go compiler + go mod cache → distroless runtime'
    df = (Dockerfile()
        .from_(f'golang:{go_version}-alpine', as_='builder')
        .workdir('/src')
        .copy('go.mod', '.').copy('go.sum', '.')
        .run_mount('go mod download', target='/go/pkg/mod')
        .copy('.', '.')
        .env('CGO_ENABLED', '0' if not cgo else '1')
        .run('go build -ldflags="-s -w" -o /app .')
        .from_(runtime)
        .copy('/app', '/app', from_='builder')
        .expose(port))
    return df.cmd(cmd or ['/app'])

# %% ../nbs/05_apps.ipynb #0bd469c0
def rust_app(port=8080, rust_version='1', binary='app', runtime='gcr.io/distroless/static',
             features=None, release=True):
    'Two-stage Rust Dockerfile: cargo build → distroless runtime'
    build_cmd = 'cargo build --release' + (f' --features {features}' if features else '')
    df = (Dockerfile()
        .from_(f'rust:{rust_version}-slim-bookworm', as_='builder')
        .workdir('/src')
        .copy('.', '.')
        .run_mount(build_cmd, target='/usr/local/cargo/registry')
        .from_(runtime)
        .copy(f'/src/target/release/{binary}', f'/{binary}', from_='builder')
        .expose(port))
    return df.cmd([f'/{binary}'])
