"""AWS CLI wrapper and opinionated resource builders"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_aws.ipynb.

# %% auto #0
__all__ = ['aws_cli', 'callaws', 'Aws', 'vpc', 'subnet', 'security_group', 'ecr_repo', 
           'ecs_cluster', 'ecs_service', 'rds_postgres', 'aws_stack']

# %% ../nbs/12_aws.ipynb
import json
import os
import subprocess
from .core import Cli

# %% ../nbs/12_aws.ipynb
def callaws(*args):
    'Run aws CLI command, return JSON output'
    result = subprocess.run(('aws',) + args + ('--output', 'json'),
                            capture_output=True, text=True, check=True)
    try:
        return json.loads(result.stdout)
    except:
        return result.stdout.strip()

class Aws(Cli):
    'Wrap AWS CLI: __getattr__ dispatches subcommands, kwargs become flags'
    def _run(self, cmd, *args): return callaws(cmd, *args)

aws_cli = Aws()

# %% ../nbs/12_aws.ipynb
# Enterprise security group rules
_ENTERPRISE_SG_RULES = [
    {'IpProtocol': 'tcp', 'FromPort': 443, 'ToPort': 443, 'IpRanges': [{'CidrIp': '0.0.0.0/0'}]},
    {'IpProtocol': 'tcp', 'FromPort': 80, 'ToPort': 80, 'IpRanges': [{'CidrIp': '0.0.0.0/0'}]},
]

# %% ../nbs/12_aws.ipynb
def vpc(name, cidr='10.0.0.0/16'):
    'Create AWS VPC'
    result = callaws('ec2', 'create-vpc', '--cidr-block', cidr)
    vpc_id = result['Vpc']['VpcId']
    
    # Tag the VPC
    callaws('ec2', 'create-tags',
            '--resources', vpc_id,
            '--tags', f'Key=Name,Value={name}')
    
    return result

# %% ../nbs/12_aws.ipynb
def subnet(name, vpc_id, cidr='10.0.1.0/24', az=None):
    'Create AWS subnet'
    args = ['ec2', 'create-subnet',
            '--vpc-id', vpc_id,
            '--cidr-block', cidr]
    
    if az:
        args.extend(['--availability-zone', az])
    
    result = callaws(*args)
    subnet_id = result['Subnet']['SubnetId']
    
    # Tag the subnet
    callaws('ec2', 'create-tags',
            '--resources', subnet_id,
            '--tags', f'Key=Name,Value={name}')
    
    return result

# %% ../nbs/12_aws.ipynb
def security_group(name, vpc_id, rules=None):
    'Create security group with enterprise defaults'
    # Create security group
    result = callaws('ec2', 'create-security-group',
                     '--group-name', name,
                     '--description', f'Security group for {name}',
                     '--vpc-id', vpc_id)
    
    sg_id = result['GroupId']
    
    # Add ingress rules
    rule_list = rules if rules else _ENTERPRISE_SG_RULES
    for rule in rule_list:
        callaws('ec2', 'authorize-security-group-ingress',
                '--group-id', sg_id,
                '--ip-permissions', json.dumps([rule]))
    
    return result

# %% ../nbs/12_aws.ipynb
def ecr_repo(name):
    'Create ECR repository with image scanning on push'
    return callaws('ecr', 'create-repository',
                   '--repository-name', name,
                   '--image-scanning-configuration', 'scanOnPush=true')

# %% ../nbs/12_aws.ipynb
def ecs_cluster(name):
    'Create ECS cluster'
    return callaws('ecs', 'create-cluster', '--cluster-name', name)

# %% ../nbs/12_aws.ipynb
def ecs_service(name, cluster, image, port=8080, cpu='256', memory='512',
                env_vars=None, desired_count=1):
    'Create ECS Fargate task definition and service'
    # Create task definition
    container_def = {
        'name': name,
        'image': image,
        'portMappings': [{'containerPort': port, 'protocol': 'tcp'}],
        'essential': True,
    }
    
    if env_vars:
        container_def['environment'] = [
            {'name': k, 'value': str(v)} for k, v in env_vars.items()
        ]
    
    task_def = {
        'family': name,
        'networkMode': 'awsvpc',
        'requiresCompatibilities': ['FARGATE'],
        'cpu': cpu,
        'memory': memory,
        'containerDefinitions': [container_def]
    }
    
    # Register task definition
    task_result = callaws('ecs', 'register-task-definition',
                          '--cli-input-json', json.dumps(task_def))
    
    # Create service (simplified - in production would need subnets, security groups, load balancer)
    service_result = callaws('ecs', 'create-service',
                             '--cluster', cluster,
                             '--service-name', name,
                             '--task-definition', name,
                             '--desired-count', str(desired_count),
                             '--launch-type', 'FARGATE')
    
    return {
        'task_definition': task_result,
        'service': service_result
    }

# %% ../nbs/12_aws.ipynb
def rds_postgres(name, instance_class='db.t3.micro', engine_version='16',
                 storage=20, username='appadmin'):
    'Create RDS PostgreSQL instance with encryption'
    password = os.environ.get('POSTGRES_PASSWORD')
    if not password:
        raise ValueError('POSTGRES_PASSWORD environment variable required')
    
    return callaws('rds', 'create-db-instance',
                   '--db-instance-identifier', name,
                   '--db-instance-class', instance_class,
                   '--engine', 'postgres',
                   '--engine-version', engine_version,
                   '--master-username', username,
                   '--master-user-password', password,
                   '--allocated-storage', str(storage),
                   '--storage-encrypted',
                   '--publicly-accessible', 'false')

# %% ../nbs/12_aws.ipynb
def aws_stack(app_name, region='us-east-1', image=None, port=8080,
              postgres=False, registry=False):
    'High-level AWS orchestrator: creates all resources for a web app'
    result = {
        'app_name': app_name,
        'region': region,
    }
    
    # Create VPC
    print(f'Creating VPC for {app_name}...')
    vpc_result = vpc(f'{app_name}-vpc')
    vpc_id = vpc_result['Vpc']['VpcId']
    result['vpc_id'] = vpc_id
    
    # Create subnets (2 for high availability)
    print('Creating subnets...')
    subnet1 = subnet(f'{app_name}-subnet-1', vpc_id, '10.0.1.0/24')
    subnet2 = subnet(f'{app_name}-subnet-2', vpc_id, '10.0.2.0/24')
    result['subnets'] = [
        subnet1['Subnet']['SubnetId'],
        subnet2['Subnet']['SubnetId']
    ]
    
    # Create security group
    print('Creating security group...')
    sg = security_group(f'{app_name}-sg', vpc_id)
    result['security_group'] = sg['GroupId']
    
    # Create ECR if requested
    if registry:
        print(f'Creating ECR repository...')
        ecr = ecr_repo(app_name)
        result['registry'] = ecr['repository']['repositoryUri']
    
    # Create RDS if requested
    if postgres:
        print('Creating RDS PostgreSQL...')
        db = rds_postgres(f'{app_name}-db')
        result['database'] = {
            'endpoint': db['DBInstance']['Endpoint']['Address'],
            'port': db['DBInstance']['Endpoint']['Port'],
            'name': f'{app_name}-db',
            'username': 'appadmin'
        }
    
    # Create ECS cluster
    print('Creating ECS cluster...')
    cluster = ecs_cluster(f'{app_name}-cluster')
    result['cluster'] = cluster['cluster']['clusterArn']
    
    # Create ECS service if image provided
    if image:
        print('Creating ECS service...')
        svc = ecs_service(app_name, f'{app_name}-cluster', image, port)
        result['service'] = svc['service']['serviceArn']
    
    return result
