"""Azure CLI wrapper and opinionated resource builders"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_azure.ipynb.

# %% auto #0
__all__ = ['az', 'callaz', 'Az', 'resource_group', 'vnet', 'nsg', 'container_registry', 
           'container_app_env', 'container_app', 'managed_postgres', 'azure_stack']

# %% ../nbs/11_azure.ipynb
import json
import os
import subprocess
from .core import Cli

# %% ../nbs/11_azure.ipynb
def callaz(*args):
    'Run az CLI command, return JSON output'
    result = subprocess.run(('az',) + args + ('--output', 'json'),
                            capture_output=True, text=True, check=True)
    try:
        return json.loads(result.stdout)
    except:
        return result.stdout.strip()

class Az(Cli):
    'Wrap Azure CLI: __getattr__ dispatches subcommands, kwargs become flags'
    def _run(self, cmd, *args): return callaz(cmd, *args)

az = Az()

# %% ../nbs/11_azure.ipynb
# Enterprise NSG rules
_ENTERPRISE_NSG_RULES = [
    {
        'name': 'AllowHTTPS',
        'priority': 100,
        'direction': 'Inbound',
        'access': 'Allow',
        'protocol': 'Tcp',
        'source-port-ranges': '*',
        'destination-port-ranges': '443',
        'source-address-prefixes': '*',
        'destination-address-prefixes': '*'
    },
    {
        'name': 'AllowHTTP',
        'priority': 110,
        'direction': 'Inbound',
        'access': 'Allow',
        'protocol': 'Tcp',
        'source-port-ranges': '*',
        'destination-port-ranges': '80',
        'source-address-prefixes': '*',
        'destination-address-prefixes': '*'
    },
    {
        'name': 'DenyAllInbound',
        'priority': 4096,
        'direction': 'Inbound',
        'access': 'Deny',
        'protocol': '*',
        'source-port-ranges': '*',
        'destination-port-ranges': '*',
        'source-address-prefixes': '*',
        'destination-address-prefixes': '*'
    }
]

# %% ../nbs/11_azure.ipynb
def resource_group(name, location='eastus'):
    'Create Azure resource group'
    return callaz('group', 'create', '--name', name, '--location', location)

# %% ../nbs/11_azure.ipynb
def vnet(name, rg, address_prefix='10.0.0.0/16', subnet_name='default', subnet_prefix='10.0.1.0/24'):
    'Create Azure virtual network with subnet'
    return callaz('network', 'vnet', 'create',
                  '--name', name, '--resource-group', rg,
                  '--address-prefix', address_prefix,
                  '--subnet-name', subnet_name,
                  '--subnet-prefix', subnet_prefix)

# %% ../nbs/11_azure.ipynb
def nsg(name, rg, rules=None):
    'Create NSG with enterprise default rules'
    # Create NSG
    result = callaz('network', 'nsg', 'create',
                    '--name', name, '--resource-group', rg)
    
    # Add rules
    rule_list = rules if rules else _ENTERPRISE_NSG_RULES
    for rule in rule_list:
        args = ['network', 'nsg', 'rule', 'create',
                '--nsg-name', name, '--resource-group', rg]
        for key, value in rule.items():
            args.extend([f'--{key}', str(value)])
        callaz(*args)
    
    return result

# %% ../nbs/11_azure.ipynb
def container_registry(name, rg, sku='Basic'):
    'Create Azure Container Registry with admin disabled'
    return callaz('acr', 'create',
                  '--name', name, '--resource-group', rg,
                  '--sku', sku, '--admin-enabled', 'false')

# %% ../nbs/11_azure.ipynb
def container_app_env(name, rg, location='eastus'):
    'Create Azure Container Apps environment'
    return callaz('containerapp', 'env', 'create',
                  '--name', name, '--resource-group', rg,
                  '--location', location)

# %% ../nbs/11_azure.ipynb
def container_app(name, rg, env_name, image, port=8080, 
                  cpu='0.5', memory='1.0Gi', env_vars=None,
                  min_replicas=1, max_replicas=3):
    'Create Azure Container App with external ingress'
    args = ['containerapp', 'create',
            '--name', name, '--resource-group', rg,
            '--environment', env_name,
            '--image', image,
            '--target-port', str(port),
            '--ingress', 'external',
            '--cpu', cpu, '--memory', memory,
            '--min-replicas', str(min_replicas),
            '--max-replicas', str(max_replicas)]
    
    if env_vars:
        env_list = [f'{k}={v}' for k, v in env_vars.items()]
        args.extend(['--env-vars', ' '.join(env_list)])
    
    return callaz(*args)

# %% ../nbs/11_azure.ipynb
def managed_postgres(name, rg, sku='Standard_B1ms', version='16',
                     storage_size=32, admin_user='appadmin'):
    'Create Azure managed PostgreSQL flexible server'
    password = os.environ.get('POSTGRES_PASSWORD')
    if not password:
        raise ValueError('POSTGRES_PASSWORD environment variable required')
    
    return callaz('postgres', 'flexible-server', 'create',
                  '--name', name, '--resource-group', rg,
                  '--sku-name', sku, '--version', version,
                  '--storage-size', str(storage_size),
                  '--admin-user', admin_user,
                  '--admin-password', password,
                  '--public-access', 'None')

# %% ../nbs/11_azure.ipynb
def azure_stack(app_name, location='eastus', image=None, port=8080,
                postgres=False, registry=False):
    'High-level Azure orchestrator: creates all resources for a web app'
    rg_name = f'{app_name}-rg'
    vnet_name = f'{app_name}-vnet'
    nsg_name = f'{app_name}-nsg'
    env_name = f'{app_name}-env'
    
    result = {
        'app_name': app_name,
        'location': location,
        'resource_group': rg_name,
    }
    
    # Create resource group
    print(f'Creating resource group {rg_name}...')
    resource_group(rg_name, location)
    
    # Create VNet
    print(f'Creating virtual network {vnet_name}...')
    vnet(vnet_name, rg_name)
    result['vnet'] = vnet_name
    
    # Create NSG
    print(f'Creating network security group {nsg_name}...')
    nsg(nsg_name, rg_name)
    result['nsg'] = nsg_name
    
    # Create Container Registry if requested
    if registry:
        acr_name = app_name.replace('-', '').replace('_', '')[:50]
        print(f'Creating container registry {acr_name}...')
        container_registry(acr_name, rg_name)
        result['registry'] = f'{acr_name}.azurecr.io'
    
    # Create PostgreSQL if requested
    if postgres:
        db_name = f'{app_name}-db'
        print(f'Creating managed PostgreSQL {db_name}...')
        db = managed_postgres(db_name, rg_name)
        result['database'] = {
            'host': db.get('fullyQualifiedDomainName'),
            'name': db_name,
            'user': 'appadmin'
        }
    
    # Create Container App Environment
    print(f'Creating container app environment {env_name}...')
    container_app_env(env_name, rg_name, location)
    result['environment'] = env_name
    
    # Create Container App if image provided
    if image:
        print(f'Creating container app {app_name}...')
        app = container_app(app_name, rg_name, env_name, image, port)
        result['app_url'] = app.get('properties', {}).get('configuration', {}).get('ingress', {}).get('fqdn')
    
    return result
