"""Caddy reverse proxy, CrowdSec security, and Cloudflare tunnel support"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_caddy.ipynb.

# %% auto #0
__all__ = ['caddyfile', 'caddy', 'cloudflared_svc', 'crowdsec']

# %% ../nbs/02_caddy.ipynb #e67b555b
from pathlib import Path
from fastcore.all import listify

# %% ../nbs/02_caddy.ipynb #d1a11e12
def caddyfile(domain, app='app', port=5001, *,
              dns=None, email=None, crowdsec=False, cloudflared=False):
    'Minimal Caddyfile for reverse-proxying app:port from domain'
    g = []
    if email: g += [f'    email {email}']
    if dns:
        p, tenv = (dns, f'{dns.upper()}_API_TOKEN') if isinstance(dns, str) else dns
        g += [f'    acme_dns {p} {{${tenv}}}']
    if crowdsec:
        g += ['    crowdsec {',
              '        api_url http://crowdsec:8080',
              '        api_key {$CROWDSEC_API_KEY}',
              '    }']
    s = []
    if crowdsec: s += ['    crowdsec']
    s += [f'    reverse_proxy {app}:{port}']
    prefix = 'http://' if cloudflared else ''
    parts = []
    if g: parts.append('{\n' + '\n'.join(g) + '\n}')
    parts.append(f'{prefix}{domain} {{\n' + '\n'.join(s) + '\n}')
    return '\n\n'.join(parts) + '\n'

# %% ../nbs/02_caddy.ipynb #2aaa95f8
_CADDY_IMG = {
    (False, False): 'caddy:2',
    (True,  False): 'serfriz/caddy-crowdsec:latest',
    (False, True):  'serfriz/caddy-cloudflare:latest',
    (True,  True):  'ghcr.io/buildplan/csdp-caddy:latest',
}

def caddy(domain, app='app', port=5001, *,
          dns=None, email=None, crowdsec=False, cloudflared=False,
          conf='Caddyfile', **kw):
    'Write Caddyfile and return Caddy service kwargs for Compose.svc()'
    Path(conf).write_text(
        caddyfile(domain, app, port, dns=dns, email=email,
                  crowdsec=crowdsec, cloudflared=cloudflared))
    img = _CADDY_IMG.get((crowdsec, dns == 'cloudflare'),
                          f'serfriz/caddy-{dns}:latest' if dns else 'caddy:2')
    env = {}
    if dns == 'cloudflare': env['CLOUDFLARE_API_TOKEN'] = '${CLOUDFLARE_API_TOKEN}'
    if dns == 'duckdns':    env['DUCKDNS_TOKEN']        = '${DUCKDNS_TOKEN}'
    if crowdsec:            env['CROWDSEC_API_KEY']      = '${CROWDSEC_API_KEY}'
    return dict(
        image=img, env=env or None,
        ports=None if cloudflared else ['80:80', '443:443', '443:443/udp'],
        volumes={f'./{conf}': '/etc/caddy/Caddyfile',
                 'caddy_data': '/data', 'caddy_config': '/config'},
        networks=['web'], depends_on=[app], restart='unless-stopped',
    ) | kw

# %% ../nbs/02_caddy.ipynb #52a33e28
def cloudflared_svc(token_env='CF_TUNNEL_TOKEN', **kw):
    'Cloudflare tunnel service kwargs for Compose.svc()'
    return dict(
        image='cloudflare/cloudflared:latest',
        command='tunnel --no-autoupdate run',
        env={'TUNNEL_TOKEN': f'${{{token_env}}}'},
        restart='unless-stopped',
    ) | kw

# %% ../nbs/02_caddy.ipynb #a63a6718
def crowdsec(collections=None, bouncer_key_env='CROWDSEC_BOUNCER_KEY', **kw):
    'CrowdSec agent service kwargs for Compose.svc()'
    cols = ' '.join(listify(collections) or [
        'crowdsecurity/linux', 'crowdsecurity/caddy', 'crowdsecurity/http-cve'])
    return dict(
        image='crowdsecurity/crowdsec:latest',
        env={'COLLECTIONS': cols, 'BOUNCER_KEY_caddy': f'${{{bouncer_key_env}}}'},
        volumes={'crowdsec-db': '/var/lib/crowdsec/data',
                 'crowdsec-config': '/etc/crowdsec'},
        networks=['web'], restart='unless-stopped',
    ) | kw
