"""Enterprise security and compliance presets"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_compliance.ipynb.

# %% auto #0
__all__ = ['compliance_cmds', 'harden_dockerfile', 'harden_service', 'logging_svc', 'monitoring_svc', 'scan_image', 
           'soc2_defaults', 'hipaa_defaults', 'iso27001_defaults']

# %% ../nbs/09_compliance.ipynb
import subprocess
from pathlib import Path

# %% ../nbs/09_compliance.ipynb
# Cloud-init hardening commands
_SSH_HARDENING = [
    "sed -i 's/#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config",
    "sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config",
    "sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords no/' /etc/ssh/sshd_config",
    "echo 'MaxAuthTries 3' >> /etc/ssh/sshd_config",
    "echo 'LoginGraceTime 30' >> /etc/ssh/sshd_config",
    "echo 'Protocol 2' >> /etc/ssh/sshd_config",
    "systemctl restart sshd",
]

_AUTO_UPDATES = [
    "apt-get update",
    "apt-get install -y unattended-upgrades",
    "echo 'APT::Periodic::Update-Package-Lists \"1\";' > /etc/apt/apt.conf.d/20auto-upgrades",
    "echo 'APT::Periodic::Unattended-Upgrade \"1\";' >> /etc/apt/apt.conf.d/20auto-upgrades",
    "systemctl enable unattended-upgrades",
]

_FAIL2BAN = [
    "apt-get install -y fail2ban",
    "systemctl enable fail2ban",
    "systemctl start fail2ban",
]

_AUDITD = [
    "apt-get install -y auditd",
    "systemctl enable auditd",
    "auditctl -w /var/log/auth.log -p wa -k auth",
    "auditctl -w /etc/sudoers -p wa -k sudoers",
    "auditctl -w /usr/bin/docker -p x -k docker",
]

_KERNEL_HARDENING = [
    "echo 'net.ipv4.conf.all.rp_filter=1' >> /etc/sysctl.conf",
    "echo 'net.ipv4.conf.default.rp_filter=1' >> /etc/sysctl.conf",
    "echo 'net.ipv4.conf.all.accept_source_route=0' >> /etc/sysctl.conf",
    "echo 'net.ipv4.conf.default.accept_source_route=0' >> /etc/sysctl.conf",
    "echo 'net.ipv4.tcp_syncookies=1' >> /etc/sysctl.conf",
    "echo 'net.ipv4.conf.all.log_martians=1' >> /etc/sysctl.conf",
    "echo 'net.ipv4.conf.default.log_martians=1' >> /etc/sysctl.conf",
    "echo 'net.ipv4.conf.all.accept_redirects=0' >> /etc/sysctl.conf",
    "echo 'net.ipv4.conf.default.accept_redirects=0' >> /etc/sysctl.conf",
    "sysctl -p",
]

# %% ../nbs/09_compliance.ipynb
def compliance_cmds(level='soc2'):
    'Return cloud-init runcmd list based on compliance level'
    if level == 'basic':
        return _SSH_HARDENING + _AUTO_UPDATES + _FAIL2BAN
    elif level in ['soc2', 'iso27001']:
        return _SSH_HARDENING + _AUTO_UPDATES + _FAIL2BAN + _AUDITD + _KERNEL_HARDENING
    elif level == 'hipaa':
        hipaa_extras = [
            "dd if=/dev/zero of=/swapfile bs=1M count=2048",
            "chmod 600 /swapfile",
            "mkswap /swapfile",
            "cryptsetup luksFormat /swapfile",
            "echo 'TMOUT=900' >> /etc/profile",
            "echo 'readonly TMOUT' >> /etc/profile",
            "echo 'export TMOUT' >> /etc/profile",
            "echo 'PROMPT_COMMAND=\"history -a\"' >> /etc/profile",
        ]
        return _SSH_HARDENING + _AUTO_UPDATES + _FAIL2BAN + _AUDITD + _KERNEL_HARDENING + hipaa_extras
    return []

# %% ../nbs/09_compliance.ipynb
def harden_dockerfile(df, user='appuser', uid=1000, healthcheck_path=None, port=8080):
    'Add security hardening to a Dockerfile builder'
    df = df.run([
        f'groupadd -g {uid} {user}',
        f'useradd -r -u {uid} -g {user} {user}',
        'chown -R {user}:{user} /app'
    ])
    df = df.user(user)
    if healthcheck_path:
        df = df.healthcheck(f'curl -f http://localhost:{port}{healthcheck_path}', i='30s', t='5s', r='3')
    df = df.label(
        maintainer='fastops',
        version='1.0',
        compliance_hardened='true'
    )
    return df

# %% ../nbs/09_compliance.ipynb
def harden_service(svc_kwargs, *, read_only=True, no_new_privs=True, drop_caps=True, tmpfs=None):
    'Mutate and return service dict with security hardening'
    if read_only:
        svc_kwargs['read_only'] = True
    if no_new_privs:
        svc_kwargs.setdefault('security_opt', []).append('no-new-privileges:true')
    if drop_caps:
        svc_kwargs['cap_drop'] = ['ALL']
    if tmpfs:
        svc_kwargs['tmpfs'] = tmpfs if isinstance(tmpfs, list) else [tmpfs]
    return svc_kwargs

# %% ../nbs/09_compliance.ipynb
def logging_svc(provider='loki', **kw):
    'Return Compose service kwargs for centralized logging'
    if provider == 'loki':
        return {
            'image': 'grafana/loki:latest',
            'ports': {3100: 3100},
            'command': '-config.file=/etc/loki/local-config.yaml',
            'restart': 'unless-stopped',
            **kw
        }
    elif provider == 'vector':
        return {
            'image': 'timberio/vector:latest-alpine',
            'volumes': {
                '/var/run/docker.sock': '/var/run/docker.sock:ro',
                './vector.toml': '/etc/vector/vector.toml:ro'
            },
            'restart': 'unless-stopped',
            **kw
        }
    elif provider == 'fluentbit':
        return {
            'image': 'fluent/fluent-bit:latest',
            'volumes': {
                '/var/run/docker.sock': '/var/run/docker.sock:ro',
                './fluent-bit.conf': '/fluent-bit/etc/fluent-bit.conf:ro'
            },
            'restart': 'unless-stopped',
            **kw
        }
    return {}

# %% ../nbs/09_compliance.ipynb
def monitoring_svc(**kw):
    'Return Compose service kwargs for Prometheus monitoring'
    return {
        'image': 'prom/prometheus:latest',
        'ports': {9090: 9090},
        'volumes': {
            './prometheus.yml': '/etc/prometheus/prometheus.yml:ro'
        },
        'command': '--config.file=/etc/prometheus/prometheus.yml',
        'restart': 'unless-stopped',
        **kw
    }

# %% ../nbs/09_compliance.ipynb
def scan_image(image_or_tag, scanner='trivy', fail_on='HIGH,CRITICAL'):
    'Scan container image for vulnerabilities'
    result = {
        'passed': False,
        'output': '',
        'errors': [],
        'image': image_or_tag
    }
    
    try:
        if scanner == 'trivy':
            res = subprocess.run(
                ['trivy', 'image', '--severity', fail_on, '--exit-code', '1', image_or_tag],
                capture_output=True, text=True, timeout=300
            )
            result['output'] = res.stdout
            result['passed'] = res.returncode == 0
            if res.stderr:
                result['errors'].append(res.stderr)
        elif scanner == 'grype':
            res = subprocess.run(
                ['grype', image_or_tag, '--fail-on', fail_on.lower()],
                capture_output=True, text=True, timeout=300
            )
            result['output'] = res.stdout
            result['passed'] = res.returncode == 0
            if res.stderr:
                result['errors'].append(res.stderr)
    except subprocess.TimeoutExpired:
        result['errors'].append('Scan timed out after 5 minutes')
    except FileNotFoundError:
        result['errors'].append(f'{scanner} not found in PATH')
    except Exception as e:
        result['errors'].append(str(e))
    
    return result

# %% ../nbs/09_compliance.ipynb
def soc2_defaults():
    'SOC 2 compliance preset configuration'
    return {
        'cloud_init_cmds': compliance_cmds('soc2'),
        'proxy_preset': 'production',
        'crowdsec': True,
        'tunnel': False,
        'harden_dockerfile': True,
        'harden_services': True,
        'logging': 'loki',
        'scanning': True,
    }

# %% ../nbs/09_compliance.ipynb
def hipaa_defaults():
    'HIPAA compliance preset configuration'
    base = soc2_defaults()
    base.update({
        'cloud_init_cmds': compliance_cmds('hipaa'),
        'encryption_at_rest': True,
        'require_baa': True,
        'allowed_providers': ['azure', 'aws', 'gcp'],
        'backup': True,
    })
    return base

# %% ../nbs/09_compliance.ipynb
def iso27001_defaults():
    'ISO 27001 compliance preset configuration'
    base = soc2_defaults()
    base.update({
        'cloud_init_cmds': compliance_cmds('iso27001'),
        'data_residency': None,  # User must set
    })
    return base
