"""Dockerfile generation, image building, container running, and testing"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['dk', 'Dockerfile', 'calldocker', 'Docker', 'test', 'run', 'containers', 'images', 'stop', 'logs', 'rm', 'rmi']

# %% ../nbs/00_core.ipynb #c7b52454175ab4d4
import re, json, subprocess
from pathlib import Path
from functools import partial
from fastcore.all import listify, joins, is_listy, L, patch, concat

# %% ../nbs/00_core.ipynb #t1qbqvj053
def _build_flags(*a, **kw):
    'Build CLI flag list: single-char kwargs → -k [v], multi-char → --key[=v]'
    k2f = lambda k: f'--{k.rstrip("_").replace("_","-")}'
    flags = list(a)
    flags += concat([f'-{k}', str(v)] for k,v in kw.items() if len(k) == 1 and v not in (True, False, None))
    flags += [f'-{k}' for k,v in kw.items() if len(k) == 1 and v is True]
    flags += [f'{k2f(k)}={v}' for k,v in kw.items() if len(k) > 1 and v not in (True, False, None)]
    flags += [k2f(k) for k,v in kw.items() if len(k) > 1 and v is True]
    return flags

# %% ../nbs/00_core.ipynb #112779e5025a332d
def _instr(kw, v): return f'{kw} {v}'

# %% ../nbs/00_core.ipynb #5d14b9bf7a117b3c
def _from(image:str, tag:str=None, as_:str=None) -> str:
    'From instruction -- base image with optional tag and alias'
    return _instr('FROM', f'{image}{f":{tag}" if tag else ""}{f" AS {as_}" if as_ else ""}')

# %% ../nbs/00_core.ipynb #5749a2a4ac1b4fa9
def _run(cmd: list | str):
    'RUN instruction -- execute command(s) in shell'
    return _instr('RUN', joins(' && ', listify(cmd)))

# %% ../nbs/00_core.ipynb #r49lgjh5y2i
def _apt_install(*pkgs, y=False):
    'RUN apt-get update && apt-get install packages'
    flag = '-y ' if y else ''
    return _run(['apt-get update', f'apt-get install {flag}{" ".join(pkgs)}'])

# %% ../nbs/00_core.ipynb #ee7840b601f4f546
def _cmd(cmd: list | str):
    "CMD instruction -- default command for container"
    return _instr('CMD', json.dumps(cmd) if is_listy(cmd) else cmd)

# %% ../nbs/00_core.ipynb #f3e6c641b8c5eb53
def _copy(src:str, dst:str, from_:str=None, link=False):
    'COPY instruction -- copy files into image'
    flags = f'{"--link " if link else ""}{"--from=" + from_ + " " if from_ else ""}'
    return _instr('COPY', f'{flags}{src} {dst}')

# %% ../nbs/00_core.ipynb #c9ae4a4f4f2e1d4e
def _add(src:str, dst:str):
    'ADD instruction -- copy files/URLs into image'
    return _instr('ADD', f'{src} {dst}')

# %% ../nbs/00_core.ipynb #5a3fa65a053082d9
def _workdir(path):
    'WORKDIR instruction -- set working directory'
    return _instr('WORKDIR', path)

# %% ../nbs/00_core.ipynb #7ac5673990f345da
def _env(k, v=None):
    'ENV instruction -- set environment variable'
    return _instr('ENV', f'{k}{"=" + str(v) if v else ""}')

# %% ../nbs/00_core.ipynb #83047e4ca88feace
def _expose(port):
    'EXPOSE instruction -- declare container port'
    return _instr('EXPOSE', str(port))

# %% ../nbs/00_core.ipynb #9b0c728427144919
def _entrypoint(cmd):
    'ENTRYPOINT instruction -- container entrypoint'
    return _instr('ENTRYPOINT', json.dumps(cmd) if is_listy(cmd) else cmd)

# %% ../nbs/00_core.ipynb #e50bfa8ecc6627f7
def _arg(nm, def_=None):
    'ARG instruction -- build-time variable'
    return _instr('ARG', f'{nm}{"=" + str(def_) if def_ else ""}')

# %% ../nbs/00_core.ipynb #c09c6ddb6ffca82a
def _label(**kw):
    'LABEL instruction -- image metadata'
    return _instr('LABEL', joins(' ', (f'{k}="{v}"' for k, v in kw.items())))

# %% ../nbs/00_core.ipynb #d32f1a3ff26af0e9
def _user(u):
    'USER instruction -- set runtime user'
    return _instr('USER', u)

# %% ../nbs/00_core.ipynb #53e15d4c987c26cd
def _volume(path):
    'VOLUME instruction -- declare mount point'
    return _instr('VOLUME', json.dumps(path) if is_listy(path) else path)

# %% ../nbs/00_core.ipynb #c87ef358273c8983
def _shell(cmd):
    'SHELL instruction -- override default shell'
    return _instr('SHELL', json.dumps(cmd))

# %% ../nbs/00_core.ipynb #be7c4e02a7981ea
def _healthcheck(cmd, i=None, t=None, r=None, sp=None):
    'HEALTHCHECK instruction -- container health check'
    kw = {'interval': i, 'timeout': t, 'retries': r, 'start-period': sp}
    opts = joins(' ', [f'--{k}={v}' for k,v in kw.items() if v])
    c = json.dumps(cmd) if is_listy(cmd) else cmd
    return _instr('HEALTHCHECK', f'{opts} CMD {c}'.strip())

# %% ../nbs/00_core.ipynb #e824ecd74f59baa2
def _stop_sig_(sig):
    'STOPSIGNAL instruction -- set stop signal'
    return _instr('STOPSIGNAL', sig)

# %% ../nbs/00_core.ipynb #43fa905903a7a50
def _on_build(ins):
    'ONBUILD instruction -- trigger for downstream builds'
    return _instr('ONBUILD', str(ins))

# %% ../nbs/00_core.ipynb #15ja7m700to
def _parse(path_or_str: Path | str):
    'Parse Dockerfile text into list of instruction strings'
    t = Path(path_or_str).read_text() if isinstance(path_or_str, Path) else path_or_str
    return L.splitlines(re.sub(r'\\\n\s*', '', t)).filter(lambda l: l.strip() and not l.strip().startswith('#'))

# %% ../nbs/00_core.ipynb #77afa11b44a44293
class Dockerfile(L):
    'Fluent builder for Dockerfiles'
    def _new(self, items, **kw): return type(self)(items, use_list=None, **kw)
    @classmethod
    def load(cls, path:Path=Path('Dockerfile')): return cls(_parse(Path(path)))
    def from_(self, base, tag=None, as_=None): return self._add(_from(base, tag, as_))
    def _add(self, i): return self._new(self.items + [i])
    def run(self, cmd): return self._add(_run(cmd))
    def cmd(self, cmd): return self._add(_cmd(cmd))
    def copy(self, src, dst, from_=None, link=False): return self._add(_copy(src, dst, from_, link))
    def add(self, src, dst): return self._add(_add(src, dst))
    def workdir(self, path='/app'): return self._add(_workdir(path))
    def env(self, key, value=None): return self._add(_env(key, value))
    def expose(self, port): return self._add(_expose(port))
    def entrypoint(self, cmd): return self._add(_entrypoint(cmd))
    def arg(self, name, default=None): return self._add(_arg(name, default))
    def label(self, **kwargs): return self._add(_label(**kwargs))
    def user(self, user): return self._add(_user(user))
    def volume(self, path): return self._add(_volume(path))
    def shell(self, cmd): return self._add(_shell(cmd))
    def healthcheck(self, cmd, **kw): return self._add(_healthcheck(cmd, **kw))
    def stopsignal(self, signal): return self._add(_stop_sig_(signal))
    def onbuild(self, instruction): return self._add(_on_build(instruction))
    def apt_install(self, *pkgs, y=False): return self._add(_apt_install(*pkgs, y=y))
    def run_mount(self, cmd, type='cache', target=None, **mount_kw):
        'RUN --mount=... for build cache mounts (uv, pip, apt) and secrets'
        opts = f'type={type}'
        if target: opts += f',target={target}'
        for k, v in mount_kw.items(): opts += f',{k.replace("_","-")}={v}'
        return self._add(f'RUN --mount={opts} {cmd}')
    def __call__(self, kw, *args, **kwargs):
        'Build a generic Dockerfile instruction: kw ARG1 ARG2 --flag=val --bool-flag'
        k2f = lambda k: f'--{k.rstrip("_").replace("_","-")}'
        flags = [f'{k2f(k)}={v}' for k,v in kwargs.items() if v not in (True, False, None)]
        flags += [k2f(k) for k,v in kwargs.items() if v is True]
        return self._add(f'{kw} {" ".join([*flags, *map(str, args)])}')
    def __getattr__(self, nm):
        'Dispatch unknown instruction names: df.some_instr(arg) → SOME-INSTR arg'
        if nm.startswith('_'): raise AttributeError(nm)
        return partial(self, nm.upper().rstrip('_'))
    def __str__(self): return chr(10).join(self)
    def __repr__(self): return str(self)
    def save(self, path:Path=Path('Dockerfile')):
        Path(path).mk_write(str(self))
        return path

# %% ../nbs/00_core.ipynb #whnvww0xy2b
class _CLI:
    'Base: __call__ builds flags → _run(), __getattr__ dispatches subcommands'
    def __call__(self, cmd, *args, **kwargs): return self._run(cmd, *_build_flags(*args, **kwargs))
    def _run(self, cmd, *args): raise NotImplementedError
    def __getattr__(self, nm):
        if nm.startswith('_'): raise AttributeError(nm)
        return partial(self, nm.replace('_', '-'))

# %% ../nbs/00_core.ipynb #4abe618740a1c539
def _clean_cfg():
    'Create a docker config dir with credential helpers stripped'
    src = Path(os.environ.get('DOCKER_CONFIG', Path.home()/'.docker'))
    dst = Path.home()/'.fastops'/'config'
    cfgf = dst/'config.json'
    if cfgf.exists(): return str(dst)
    cfg = src.joinpath('config.json').read_json() if (src/'config.json').exists() else {}
    cfg.pop('credsStore', None); cfg.pop('credHelpers', None)
    cfgf.write_json(cfg)
    ctx_src, ctx_dst = src/'contexts', dst/'contexts'
    if ctx_src.exists() and not ctx_dst.exists(): ctx_dst.symlink_to(ctx_src)
    return str(dst)

def calldocker(*args, no_creds=False):
    'Run a docker CLI command, return stdout. Respects DOCKR_RUNTIME env var (default: docker).'
    rt = os.environ.get('DOCKR_RUNTIME', 'docker')
    pre = ('--config', _clean_cfg()) if no_creds and rt == 'docker' else ()
    return subprocess.run((rt,) + pre + args, capture_output=True, text=True, check=True).stdout.strip()

class Docker(_CLI):
    'Wrap docker CLI: __getattr__ dispatches subcommands, kwargs become flags'
    def __init__(self, no_creds=False): self.no_creds = no_creds
    def _run(self, cmd, *args): return calldocker(cmd, *args, no_creds=self.no_creds)

dk = Docker()

# %% ../nbs/00_core.ipynb #ae10280a7aae03af
@patch
def build(df:Dockerfile, tag:str=None, path:str='.', rm=True, no_creds=False):
    'Build image from Dockerfile. path is the build context directory.'
    df.save(Path(path) / 'Dockerfile')
    Docker(no_creds=no_creds).build(str(path), t=tag, rm=rm)
    return tag

# %% ../nbs/00_core.ipynb #7c0e35aaa6ab2848
def test(img_or_tag:str, cmd):
    'Run cmd in image, return True if exit code 0'
    try: dk.run('--rm', str(img_or_tag), *listify(cmd)); return True
    except Exception: return False

# %% ../nbs/00_core.ipynb #4d7d50c77e24ddc9
def run(img_or_tag:str, detach=False, ports=None, name=None, remove=False, command=None):
    'Run a container, return container ID (detached) or output'
    args = []
    if detach: args.append('-d')
    if remove: args.append('--rm')
    if name: args += ['--name', name]
    for cp, hp in (ports or {}).items(): args += ['-p', f'{hp}:{cp.split("/")[0]}']
    return dk('run', *args, str(img_or_tag), *listify(command or []))

# %% ../nbs/00_core.ipynb #c9fa9e9480de4c3f
def containers(all=False):
    'List running containers (names)'
    return dk.ps(format='{{.Names}}', a=all).splitlines()

# %% ../nbs/00_core.ipynb #b1e4cd5b26a74b9d
def images():
    'List image tags'
    return dk.images(format='{{.Repository}}:{{.Tag}}').splitlines()

# %% ../nbs/00_core.ipynb #e95f07d40d17a92c
def stop(name_or_id:str):
    'Stop a container by name or ID'
    dk.stop(name_or_id)

# %% ../nbs/00_core.ipynb #937eef6de6b03491
def logs(name_or_id:str, n=10):
    'Tail logs of a container'
    return dk.logs(name_or_id, tail=n)

# %% ../nbs/00_core.ipynb #jjdj9t1tjhl
def rm(name_or_id:str, force=False):
    'Remove a container by name or ID'
    dk.rm(name_or_id, f=force)

# %% ../nbs/00_core.ipynb #vm8xmxstny
def rmi(image:str, force=False):
    'Remove an image by name or ID'
    dk.rmi(image, f=force)
