"""Repo language/framework auto-detection"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_detect.ipynb.

# %% auto #0
__all__ = ['detect', 'auto_dockerfile']

# %% ../nbs/08_detect.ipynb
import json
import subprocess
from pathlib import Path

# %% ../nbs/08_detect.ipynb
def _read_json(p):
    'Safe JSON read'
    try:
        return json.loads(Path(p).read_text())
    except:
        return {}

def _has_dep(path, dep):
    'Check if dependency exists in pyproject.toml or requirements.txt'
    path = Path(path)
    # Check pyproject.toml
    pyproject = path / 'pyproject.toml'
    if pyproject.exists():
        content = pyproject.read_text()
        if dep in content:
            return True
    # Check requirements.txt
    reqtxt = path / 'requirements.txt'
    if reqtxt.exists():
        content = reqtxt.read_text()
        if dep in content:
            return True
    return False

def _find_entrypoint(path):
    'Check for common entry point filenames'
    path = Path(path)
    for entry in ['main.py', 'app.py', 'server.py', 'run.py', 'manage.py']:
        if (path / entry).exists():
            return entry
    return None

# %% ../nbs/08_detect.ipynb
def detect(path='.', use_nixpacks=None):
    'Analyze a local repo directory and return detection dict'
    path = Path(path)
    result = {
        'path': str(path),
        'language': None,
        'framework': None,
        'entry': None,
        'port': None,
    }
    
    # Check for Dockerfile
    if (path / 'Dockerfile').exists():
        result['language'] = 'docker'
        result['entry'] = 'Dockerfile'
        return result
    
    # Check for Python
    if (path / 'pyproject.toml').exists() or (path / 'requirements.txt').exists():
        result['language'] = 'python'
        result['entry'] = _find_entrypoint(path)
        
        # Detect framework
        if _has_dep(path, 'python-fasthtml'):
            result['framework'] = 'fasthtml'
            result['port'] = 5001
        elif _has_dep(path, 'streamlit'):
            result['framework'] = 'streamlit'
            result['port'] = 8501
        elif _has_dep(path, 'fastapi'):
            # Check for fastapi-react pattern
            if (path / 'frontend' / 'package.json').exists():
                result['framework'] = 'fastapi-react'
            else:
                result['framework'] = 'fastapi'
            result['port'] = 8000
        elif _has_dep(path, 'flask'):
            result['framework'] = 'flask'
            result['port'] = 5000
        elif _has_dep(path, 'django'):
            result['framework'] = 'django'
            result['port'] = 8000
            result['entry'] = 'manage.py'
        else:
            result['port'] = 8000
        
        return result
    
    # Check for Go
    if (path / 'go.mod').exists():
        result['language'] = 'go'
        result['framework'] = 'go'
        result['port'] = 8080
        result['entry'] = 'main.go'
        return result
    
    # Check for Rust
    if (path / 'Cargo.toml').exists():
        result['language'] = 'rust'
        result['framework'] = 'rust'
        result['port'] = 8080
        # Extract binary name from Cargo.toml
        try:
            cargo = (path / 'Cargo.toml').read_text()
            for line in cargo.split('\n'):
                if line.strip().startswith('name'):
                    name = line.split('=')[1].strip().strip('"').strip("'")
                    result['entry'] = name
                    break
        except:
            pass
        return result
    
    # Check for Node.js
    if (path / 'package.json').exists():
        result['language'] = 'node'
        result['port'] = 3000
        pkg = _read_json(path / 'package.json')
        deps = {**pkg.get('dependencies', {}), **pkg.get('devDependencies', {})}
        if 'next' in deps:
            result['framework'] = 'nextjs'
        elif 'nuxt' in deps:
            result['framework'] = 'nuxt'
        result['entry'] = 'package.json'
        return result
    
    # Try nixpacks if enabled
    if use_nixpacks is not False:
        try:
            res = subprocess.run(
                ['nixpacks', 'plan', str(path), '--format', 'json'],
                capture_output=True, text=True, timeout=5
            )
            if res.returncode == 0:
                plan = json.loads(res.stdout)
                if 'buildImage' in plan:
                    # Extract language from build image
                    img = plan.get('buildImage', '')
                    if 'python' in img:
                        result['language'] = 'python'
                    elif 'node' in img:
                        result['language'] = 'node'
                    elif 'go' in img:
                        result['language'] = 'go'
                    elif 'rust' in img:
                        result['language'] = 'rust'
        except:
            pass
    
    return result

# %% ../nbs/08_detect.ipynb
def auto_dockerfile(path='.', port=None):
    'Generate Dockerfile based on detection. Returns (Dockerfile, framework) tuple.'
    from .apps import python_app, fasthtml_app, fastapi_react, go_app, rust_app
    
    info = detect(path, use_nixpacks=False)
    framework = info['framework'] or info['language']
    detected_port = port or info['port'] or 8080
    
    # Builder map
    builders = {
        'python': lambda: python_app(port=detected_port),
        'fasthtml': lambda: fasthtml_app(port=detected_port),
        'fastapi': lambda: python_app(cmd=['uvicorn', 'main:app', '--host', '0.0.0.0', f'--port={detected_port}'], port=detected_port),
        'fastapi-react': lambda: fastapi_react(port=detected_port),
        'flask': lambda: python_app(cmd=['flask', 'run', f'--host=0.0.0.0', f'--port={detected_port}'], port=detected_port),
        'django': lambda: python_app(cmd=['python', 'manage.py', 'runserver', f'0.0.0.0:{detected_port}'], port=detected_port),
        'streamlit': lambda: python_app(cmd=['streamlit', 'run', 'app.py', '--server.port', str(detected_port), '--server.address', '0.0.0.0'], port=detected_port),
        'go': lambda: go_app(port=detected_port),
        'rust': lambda: rust_app(port=detected_port, binary=info['entry'] or 'app'),
    }
    
    if framework in builders:
        df = builders[framework]()
        return (df, framework)
    
    # Fallback to nixpacks
    try:
        res = subprocess.run(
            ['nixpacks', 'plan', str(path), '--format', 'dockerfile'],
            capture_output=True, text=True, timeout=10
        )
        if res.returncode == 0:
            from .core import Dockerfile
            # Return the dockerfile content as a Dockerfile object
            df = Dockerfile()
            for line in res.stdout.strip().split('\n'):
                if line.strip():
                    df = df._add(line.strip())
            return (df, 'nixpacks')
    except:
        pass
    
    # Final fallback - basic Python
    return (python_app(port=detected_port), 'python')
