"""Google Cloud Platform CLI wrapper and opinionated resource builders"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_gcp.ipynb.

# %% auto #0
__all__ = ['Gcp', 'gcloud', 'gcp_stack']

# %% ../nbs/14_gcp.ipynb
import os, json, subprocess
from .core import Cli

# %% ../nbs/14_gcp.ipynb
def callgcloud(*args):
    'Run a gcloud command and return parsed JSON output'
    cmd = ['gcloud'] + list(args) + ['--format=json']
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f'gcloud error: {result.stderr}')
    return json.loads(result.stdout) if result.stdout.strip() else {}

class Gcp(Cli):
    'Google Cloud CLI wrapper'
    def _run(self, cmd, *args): return callgcloud(cmd, *args)

gcloud = Gcp()

# %% ../nbs/14_gcp.ipynb
def gcp_stack(name, *, image=None, port=8080, region='us-central1', project=None,
              postgres=False, redis=False, domain=None, min_instances=0, max_instances=10,
              memory='512Mi', cpu='1', env=None, service_account=None):
    'Deploy a containerized app to GCP Cloud Run with optional managed services'
    result = {'name': name, 'region': region, 'services': []}
    
    proj = project or os.environ.get('GCLOUD_PROJECT') or os.environ.get('GOOGLE_CLOUD_PROJECT', '')
    proj_args = ['--project', proj] if proj else []
    
    app_env = dict(env or {})
    
    # Optional: Cloud SQL (PostgreSQL)
    if postgres:
        db_instance = f'{name}-db'
        db_password = os.environ.get('DB_PASSWORD', 'changeme')
        try:
            callgcloud('sql', 'instances', 'create', db_instance,
                       '--database-version=POSTGRES_16',
                       '--tier=db-f1-micro',
                       f'--region={region}',
                       '--root-password=' + db_password,
                       *proj_args)
        except RuntimeError as e:
            if 'already exists' not in str(e).lower(): raise
        
        callgcloud('sql', 'databases', 'create', name,
                    f'--instance={db_instance}', *proj_args)
        
        app_env['DATABASE_URL'] = f'postgresql://postgres:{db_password}@/{name}?host=/cloudsql/{proj}:{region}:{db_instance}'
        result['services'].append({'type': 'cloud-sql', 'instance': db_instance})
    
    # Optional: Memorystore (Redis)
    if redis:
        redis_instance = f'{name}-redis'
        try:
            callgcloud('redis', 'instances', 'create', redis_instance,
                       f'--region={region}',
                       '--size=1',
                       '--tier=basic',
                       *proj_args)
        except RuntimeError as e:
            if 'already exists' not in str(e).lower(): raise
        
        redis_info = callgcloud('redis', 'instances', 'describe', redis_instance,
                                f'--region={region}', *proj_args)
        redis_host = redis_info.get('host', 'localhost')
        redis_port = redis_info.get('port', 6379)
        app_env['REDIS_URL'] = f'redis://{redis_host}:{redis_port}'
        result['services'].append({'type': 'memorystore', 'instance': redis_instance})
    
    # Deploy to Cloud Run
    if image:
        deploy_args = [
            'run', 'deploy', name,
            f'--image={image}',
            f'--port={port}',
            f'--region={region}',
            f'--memory={memory}',
            f'--cpu={cpu}',
            f'--min-instances={min_instances}',
            f'--max-instances={max_instances}',
            '--allow-unauthenticated',
            *proj_args,
        ]
        
        if service_account:
            deploy_args.append(f'--service-account={service_account}')
        
        if app_env:
            env_str = ','.join(f'{k}={v}' for k, v in app_env.items())
            deploy_args.append(f'--set-env-vars={env_str}')
        
        if postgres:
            deploy_args.append(f'--add-cloudsql-instances={proj}:{region}:{name}-db')
        
        deploy_result = callgcloud(*deploy_args)
        
        url = deploy_result.get('status', {}).get('url', f'https://{name}-{region}.run.app')
        result['url'] = url
        result['services'].append({'type': 'cloud-run', 'name': name, 'url': url})
    
    # Custom domain mapping
    if domain:
        try:
            callgcloud('run', 'domain-mappings', 'create',
                       f'--service={name}',
                       f'--domain={domain}',
                       f'--region={region}',
                       *proj_args)
        except RuntimeError as e:
            if 'already exists' not in str(e).lower(): raise
        result['domain'] = domain
    
    result['status'] = 'deployed'
    return result
