"""Multipass VM management for local Linux testing"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_multipass.ipynb.

# %% auto #0
__all__ = ['mp', 'callmultipass', 'Multipass', 'cloud_init_yaml', 'launch', 'vms', 'vm_ip', 'exec_', 'delete', 'transfer',
           'launch_docker_vm']

# %% ../nbs/03_multipass.ipynb #59dd5cbd
import os, json, subprocess, tempfile
from pathlib import Path
from fastcore.all import L
from .core import Cli

# %% ../nbs/03_multipass.ipynb #2e201deb
def callmultipass(*args):
    'Run a multipass CLI command, return stdout.'
    return subprocess.run(('multipass',) + args, capture_output=True, text=True, check=True).stdout.strip()

class Multipass(Cli):
    'Wrap multipass CLI: __getattr__ dispatches subcommands, kwargs become flags'
    def _run(self, cmd, *args): return callmultipass(cmd, *args)

mp = Multipass()

# %% ../nbs/03_multipass.ipynb #ef945318
def cloud_init_yaml(docker=True, packages=None, cmds=None) -> str:
    'Generate cloud-init YAML for a Multipass VM'
    pkgs = ['curl'] + list(packages or [])
    lines = ['#cloud-config', 'package_update: true', 'packages:']
    for p in pkgs:
        lines.append(f'  - {p}')
    rcmds = []
    if docker:
        rcmds += [
            'curl -fsSL https://get.docker.com | sh',
            'usermod -aG docker ubuntu',
            'systemctl enable --now docker',
        ]
    rcmds += list(cmds or [])
    if rcmds:
        lines.append('runcmd:')
        for c in rcmds:
            lines.append(f'  - {c}')
    return '\n'.join(lines) + '\n'

# %% ../nbs/03_multipass.ipynb #c63871ef
def launch(name, image='22.04', cpus=1, memory='1G', disk='10G', cloud_init=None, mounts=None):
    'Launch a Multipass VM. cloud_init can be YAML string or path to existing file.'
    args = ['--image', image, '--cpus', str(cpus), '--memory', memory, '--disk', disk]
    tmp_path = None
    if cloud_init is not None:
        if os.path.isfile(cloud_init):
            args += ['--cloud-init', cloud_init]
        else:
            fd, tmp_path = tempfile.mkstemp(suffix='.yaml')
            with os.fdopen(fd, 'w') as f:
                f.write(cloud_init)
            args += ['--cloud-init', tmp_path]
    for hp, vp in (mounts or {}).items():
        args += ['--mount', f'{hp}:{vp}']
    try:
        callmultipass('launch', name, *args)
    finally:
        if tmp_path is not None:
            Path(tmp_path).unlink(missing_ok=True)
    return name

# %% ../nbs/03_multipass.ipynb #eebed563
def vms(running=False) -> list:
    'List Multipass VM names. running=True filters to Running state.'
    lst = L(json.loads(callmultipass('list', '--format', 'json')).get('list', []))
    if running: lst = lst.filter(lambda v: v.get('state') == 'Running')
    return list(lst.itemgot('name'))

def vm_ip(name) -> str:
    'Get the IPv4 address of a Multipass VM.'
    data = json.loads(callmultipass('info', name, '--format', 'json'))
    return data['info'][name]['ipv4'][0]

def exec_(name, *cmd) -> str:
    'Run a command in a Multipass VM.'
    return callmultipass('exec', name, '--', *cmd)

def delete(name, purge=True) -> None:
    'Delete a Multipass VM.'
    mp.delete(name)
    if purge: mp.purge()

def transfer(src, dst) -> None:
    'Transfer files to/from a Multipass VM. Use "vmname:/path" for VM paths.'
    callmultipass('transfer', src, dst)

# %% ../nbs/03_multipass.ipynb #a32e6b87
def launch_docker_vm(name, image='22.04', cpus=2, memory='2G', disk='20G',
                     packages=None, mounts=None) -> str:
    'Launch a Multipass VM with Docker pre-installed. Convenience wrapper for cloud_init_yaml + launch.'
    return launch(name, image=image, cpus=cpus, memory=memory, disk=disk,
                  cloud_init=cloud_init_yaml(docker=True, packages=packages),
                  mounts=mounts)
