"""Fluent builders for Caddyfile and NginxConf with production presets"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_proxy.ipynb.

# %% auto #0
__all__ = ['Caddyfile', 'NginxConf']

# %% ../nbs/07_proxy.ipynb
from pathlib import Path
from fastcore.all import L

# %% ../nbs/07_proxy.ipynb
class Caddyfile(L):
    'Fluent builder for production-ready Caddyfiles'
    def __init__(self, domain, app='app', port=5001):
        self.domain = domain
        self.app = app
        self.port = port
        super().__init__([])
    
    def _new(self, items, **kw):
        c = type(self)(self.domain, self.app, self.port)
        c.items = items
        return c
    
    def _add(self, *items): return self._new(self.items + list(items))
    
    def email(self, addr):
        'Set ACME email'
        return self._add(('email', addr))
    
    def acme_dns(self, provider, token_env=None):
        'DNS-01 challenge'
        item = ('acme_dns', provider, token_env)
        return self._add(item)
    
    def crowdsec(self, api_url='http://crowdsec:8080', key_env='CROWDSEC_API_KEY'):
        'CrowdSec integration'
        return self._add(('crowdsec', api_url, key_env))
    
    def cloudflared(self):
        'Prefix domain with http://'
        return self._add(('cloudflared',))
    
    def compress(self):
        'Enable compression'
        return self._add(('compress',))
    
    def security_headers(self):
        'Add security headers'
        return self._add(('security_headers',))
    
    def static(self, url_path='/static', root='/app/static', cache='public, max-age=31536000, immutable'):
        'Serve static files with cache headers'
        return self._add(('static', url_path, root, cache))
    
    def cache_control(self, max_age='3600'):
        'Add cache-control on GET/HEAD'
        return self._add(('cache_control', max_age))
    
    def rate_limit(self, requests='100', window='1m'):
        'Rate limiting'
        return self._add(('rate_limit', requests, window))
    
    def cors(self, origin='*', methods='GET, POST, PUT, DELETE, OPTIONS'):
        'CORS headers'
        return self._add(('cors', origin, methods))
    
    def max_body(self, size='100m'):
        'Request body limit'
        return self._add(('max_body', size))
    
    def log(self, output='stdout'):
        'Access logging'
        return self._add(('log', output))
    
    def production(self):
        'Production preset: compression + security headers + logging'
        return self.compress().security_headers().log()
    
    def spa(self, static_dir='/app/static'):
        'SPA preset: static files with fallback to index.html'
        return self._add(('spa', static_dir))
    
    def api(self, rate='200', body='50m'):
        'API preset: rate limiting + generous body + compression'
        return self.rate_limit(rate, '1m').max_body(body).compress()
    
    def __str__(self):
        'Render full Caddyfile'
        lines = []
        
        # Global options
        for item in self:
            if item[0] == 'email':
                lines.insert(0, f'{{\n\temail {item[1]}\n}}')
        
        # Domain block
        domain_prefix = 'http://' if any(i[0] == 'cloudflared' for i in self) else ''
        lines.append(f'{domain_prefix}{self.domain} {{')
        
        # ACME DNS
        for item in self:
            if item[0] == 'acme_dns':
                token = f'{{{item[2]}}}' if item[2] else ''
                lines.append(f'\ttls {{\n\t\tdns {item[1]} {token}\n\t}}')
        
        # Compression
        if any(i[0] == 'compress' for i in self):
            lines.append('\tencode zstd gzip')
        
        # Security headers
        if any(i[0] == 'security_headers' for i in self):
            lines.append('\theader {')
            lines.append('\t\tX-Content-Type-Options nosniff')
            lines.append('\t\tX-Frame-Options DENY')
            lines.append('\t\tReferrer-Policy strict-origin-when-cross-origin')
            lines.append('\t\tX-XSS-Protection "1; mode=block"')
            lines.append('\t\tStrict-Transport-Security "max-age=31536000; includeSubDomains"')
            lines.append('\t\t-Server')
            lines.append('\t}')
        
        # CrowdSec
        for item in self:
            if item[0] == 'crowdsec':
                lines.append(f'\tcrowdsec {{')
                lines.append(f'\t\tapi_url {item[1]}')
                lines.append(f'\t\tapi_key {{{item[2]}}}')
                lines.append('\t}')
        
        # Max body
        for item in self:
            if item[0] == 'max_body':
                lines.append(f'\trequest_body {{')
                lines.append(f'\t\tmax_size {item[1]}')
                lines.append('\t}')
        
        # Rate limit
        for item in self:
            if item[0] == 'rate_limit':
                lines.append(f'\trate_limit {{')
                lines.append(f'\t\tzone dynamic {{')
                lines.append(f'\t\t\tkey {{http.request.remote_ip}}')
                lines.append(f'\t\t\tevents {item[1]}')
                lines.append(f'\t\t\twindow {item[2]}')
                lines.append('\t\t}')
                lines.append('\t}')
        
        # CORS
        for item in self:
            if item[0] == 'cors':
                lines.append('\t@options method OPTIONS')
                lines.append('\thandle @options {')
                lines.append(f'\t\theader Access-Control-Allow-Origin {item[1]}')
                lines.append(f'\t\theader Access-Control-Allow-Methods {item[2]}')
                lines.append('\t\theader Access-Control-Allow-Headers *')
                lines.append('\t\trespond 204')
                lines.append('\t}')
                lines.append(f'\theader Access-Control-Allow-Origin {item[1]}')
        
        # Static files
        for item in self:
            if item[0] == 'static':
                lines.append(f'\thandle_path {item[1]}/* {{')
                lines.append(f'\t\troot * {item[2]}')
                lines.append(f'\t\theader Cache-Control "{item[3]}"')
                lines.append('\t\tfile_server')
                lines.append('\t}')
        
        # SPA
        for item in self:
            if item[0] == 'spa':
                lines.append(f'\troot * {item[1]}')
                lines.append('\ttry_files {path} /index.html')
                lines.append('\tfile_server')
        
        # Cache control
        for item in self:
            if item[0] == 'cache_control':
                lines.append('\t@get method GET HEAD')
                lines.append('\thandle @get {')
                lines.append(f'\t\theader Cache-Control "max-age={item[1]}"')
                lines.append('\t}')
        
        # Logging
        for item in self:
            if item[0] == 'log':
                lines.append(f'\tlog {{')
                lines.append(f'\t\toutput {item[1]}')
                lines.append('\t}')
        
        # Reverse proxy (default)
        if not any(i[0] == 'spa' for i in self):
            lines.append(f'\treverse_proxy {self.app}:{self.port}')
        
        lines.append('}')
        return '\n'.join(lines)
    
    def __repr__(self): return str(self)
    
    def save(self, path='Caddyfile'):
        'Write to disk'
        Path(path).write_text(str(self))
        return path

# %% ../nbs/07_proxy.ipynb
class NginxConf(L):
    'Fluent builder for nginx/SWAG site-confs'
    def __init__(self, domain, app='app', port=5001):
        self.domain = domain
        self.app = app
        self.port = port
        super().__init__([])
    
    def _new(self, items, **kw):
        c = type(self)(self.domain, self.app, self.port)
        c.items = items
        return c
    
    def _add(self, *items): return self._new(self.items + list(items))
    
    def gzip(self, types=None, min_length=1000):
        'Gzip compression'
        if types is None:
            types = 'text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript'
        return self._add(('gzip', types, min_length))
    
    def security_headers(self):
        'Add security headers'
        return self._add(('security_headers',))
    
    def client_max_body(self, size='50m'):
        'Client max body size'
        return self._add(('client_max_body', size))
    
    def proxy_buffers(self, size='128k', count=4, busy='256k'):
        'Proxy buffer configuration'
        return self._add(('proxy_buffers', size, count, busy))
    
    def proxy_timeouts(self, connect='60s', send='60s', read='60s'):
        'Proxy timeout configuration'
        return self._add(('proxy_timeouts', connect, send, read))
    
    def websocket(self):
        'WebSocket support'
        return self._add(('websocket',))
    
    def static(self, url_path='/static', alias='/app/static', expires='1y'):
        'Static file serving'
        return self._add(('static', url_path, alias, expires))
    
    def cache_proxy(self, valid='1h'):
        'Proxy caching'
        return self._add(('cache_proxy', valid))
    
    def production(self):
        'Production preset'
        return self.gzip().security_headers().client_max_body().proxy_buffers()
    
    def api(self):
        'API preset'
        return self.production().proxy_timeouts().client_max_body('100m')
    
    def realtime(self):
        'Realtime preset'
        return self.production().websocket().proxy_timeouts(read='3600s')
    
    def __str__(self):
        'Render full nginx server block'
        lines = ['server {']
        lines.append('    listen 443 ssl;')
        lines.append(f'    server_name {self.domain};')
        lines.append('    include /config/nginx/ssl.conf;')
        lines.append('')
        
        # Gzip
        for item in self:
            if item[0] == 'gzip':
                lines.append('    gzip on;')
                lines.append(f'    gzip_types {item[1]};')
                lines.append(f'    gzip_min_length {item[2]};')
                lines.append('')
        
        # Security headers
        if any(i[0] == 'security_headers' for i in self):
            lines.append('    add_header X-Content-Type-Options nosniff;')
            lines.append('    add_header X-Frame-Options DENY;')
            lines.append('    add_header Referrer-Policy strict-origin-when-cross-origin;')
            lines.append('    add_header X-XSS-Protection "1; mode=block";')
            lines.append('    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";')
            lines.append('    proxy_hide_header X-Powered-By;')
            lines.append('    server_tokens off;')
            lines.append('')
        
        # Client max body
        for item in self:
            if item[0] == 'client_max_body':
                lines.append(f'    client_max_body_size {item[1]};')
                lines.append('')
        
        # Proxy buffers
        for item in self:
            if item[0] == 'proxy_buffers':
                lines.append(f'    proxy_buffer_size {item[1]};')
                lines.append(f'    proxy_buffers {item[2]} {item[1]};')
                lines.append(f'    proxy_busy_buffers_size {item[3]};')
                lines.append('')
        
        # Static files
        for item in self:
            if item[0] == 'static':
                lines.append(f'    location {item[1]} {{')
                lines.append(f'        alias {item[2]};')
                lines.append(f'        expires {item[3]};')
                lines.append('        add_header Cache-Control "public, immutable";')
                lines.append('    }')
                lines.append('')
        
        # Proxy caching
        for item in self:
            if item[0] == 'cache_proxy':
                lines.append(f'    proxy_cache_valid 200 {item[1]};')
                lines.append('    add_header X-Cache-Status $upstream_cache_status;')
                lines.append('')
        
        # Main location block
        lines.append('    location / {')
        lines.append(f'        proxy_pass http://{self.app}:{self.port};')
        lines.append('        include /config/nginx/proxy.conf;')
        
        # WebSocket
        if any(i[0] == 'websocket' for i in self):
            lines.append('        proxy_http_version 1.1;')
            lines.append('        proxy_set_header Upgrade $http_upgrade;')
            lines.append('        proxy_set_header Connection "upgrade";')
        
        # Proxy timeouts
        for item in self:
            if item[0] == 'proxy_timeouts':
                lines.append(f'        proxy_connect_timeout {item[1]};')
                lines.append(f'        proxy_send_timeout {item[2]};')
                lines.append(f'        proxy_read_timeout {item[3]};')
        
        lines.append('    }')
        lines.append('}')
        return '\n'.join(lines)
    
    def __repr__(self): return str(self)
    
    def save(self, path='proxy.conf'):
        'Write to disk'
        Path(path).write_text(str(self))
        return path
