"""Provider-agnostic secrets management"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_secrets.ipynb.

# %% auto #0
__all__ = ['Secrets']

# %% ../nbs/10_secrets.ipynb
import os
import subprocess

# %% ../nbs/10_secrets.ipynb
class Secrets:
    'Multi-provider secrets management'
    def __init__(self, provider='env', **kw):
        self.provider = provider
        self.config = kw
    
    def get(self, key):
        'Fetch secret value from provider'
        if self.provider == 'env':
            return os.environ.get(key)
        elif self.provider == 'azure':
            vault = self.config.get('vault')
            if not vault:
                raise ValueError('Azure provider requires vault_name in config')
            try:
                res = subprocess.run(
                    ['az', 'keyvault', 'secret', 'show', 
                     '--vault-name', vault, '--name', key, 
                     '--query', 'value', '-o', 'tsv'],
                    capture_output=True, text=True, check=True
                )
                return res.stdout.strip()
            except subprocess.CalledProcessError as e:
                return None
        elif self.provider == 'aws':
            try:
                res = subprocess.run(
                    ['aws', 'secretsmanager', 'get-secret-value',
                     '--secret-id', key,
                     '--query', 'SecretString',
                     '--output', 'text'],
                    capture_output=True, text=True, check=True
                )
                return res.stdout.strip()
            except subprocess.CalledProcessError:
                return None
        elif self.provider == 'gcp':
            project = self.config.get('project')
            if not project:
                raise ValueError('GCP provider requires project in config')
            try:
                res = subprocess.run(
                    ['gcloud', 'secrets', 'versions', 'access', 'latest',
                     f'--secret={key}',
                     f'--project={project}'],
                    capture_output=True, text=True, check=True
                )
                return res.stdout.strip()
            except subprocess.CalledProcessError:
                return None
        return None
    
    def set(self, key, value):
        'Store secret in provider'
        if self.provider == 'env':
            os.environ[key] = value
            return True
        elif self.provider == 'azure':
            vault = self.config.get('vault')
            if not vault:
                raise ValueError('Azure provider requires vault_name in config')
            try:
                subprocess.run(
                    ['az', 'keyvault', 'secret', 'set',
                     '--vault-name', vault, '--name', key,
                     '--value', value],
                    capture_output=True, text=True, check=True
                )
                return True
            except subprocess.CalledProcessError:
                return False
        elif self.provider == 'aws':
            try:
                # Try to update existing secret
                subprocess.run(
                    ['aws', 'secretsmanager', 'put-secret-value',
                     '--secret-id', key,
                     '--secret-string', value],
                    capture_output=True, text=True, check=True
                )
                return True
            except subprocess.CalledProcessError:
                # Try to create new secret
                try:
                    subprocess.run(
                        ['aws', 'secretsmanager', 'create-secret',
                         '--name', key,
                         '--secret-string', value],
                        capture_output=True, text=True, check=True
                    )
                    return True
                except subprocess.CalledProcessError:
                    return False
        elif self.provider == 'gcp':
            project = self.config.get('project')
            if not project:
                raise ValueError('GCP provider requires project in config')
            try:
                # Create secret if it doesn't exist
                subprocess.run(
                    ['gcloud', 'secrets', 'create', key,
                     f'--project={project}',
                     '--replication-policy=automatic'],
                    capture_output=True, text=True
                )
            except:
                pass
            # Add version with value
            try:
                proc = subprocess.run(
                    ['gcloud', 'secrets', 'versions', 'add', key,
                     f'--project={project}',
                     '--data-file=-'],
                    input=value, text=True,
                    capture_output=True, check=True
                )
                return True
            except subprocess.CalledProcessError:
                return False
        return False
    
    def list(self):
        'List secret names from provider'
        if self.provider == 'env':
            return list(os.environ.keys())
        elif self.provider == 'azure':
            vault = self.config.get('vault')
            if not vault:
                raise ValueError('Azure provider requires vault_name in config')
            try:
                res = subprocess.run(
                    ['az', 'keyvault', 'secret', 'list',
                     '--vault-name', vault,
                     '--query', '[].name',
                     '-o', 'tsv'],
                    capture_output=True, text=True, check=True
                )
                return res.stdout.strip().split('\n')
            except subprocess.CalledProcessError:
                return []
        elif self.provider == 'aws':
            try:
                import json
                res = subprocess.run(
                    ['aws', 'secretsmanager', 'list-secrets',
                     '--query', 'SecretList[].Name',
                     '--output', 'json'],
                    capture_output=True, text=True, check=True
                )
                return json.loads(res.stdout)
            except subprocess.CalledProcessError:
                return []
        elif self.provider == 'gcp':
            project = self.config.get('project')
            if not project:
                raise ValueError('GCP provider requires project in config')
            try:
                res = subprocess.run(
                    ['gcloud', 'secrets', 'list',
                     f'--project={project}',
                     '--format=value(name)'],
                    capture_output=True, text=True, check=True
                )
                return res.stdout.strip().split('\n')
            except subprocess.CalledProcessError:
                return []
        return []
    
    def compose_env(self, keys):
        'Resolve list of secret names, return dict for Compose service env'
        return {key: self.get(key) for key in keys if self.get(key) is not None}
