"""VPS provisioning: cloud-init generation, Hetzner hcloud CLI wrapper, SSH deployment helpers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_vps.ipynb.

# %% auto #0
__all__ = ['mp', 'dock_cmd', 'Multipass', 'deploy_mp', 'vps_init', 'multi_init', 'hetz', 'create', 'servers', 'server_ip',
           'delete', 'hetz_keys', 'hetz_key_names', 'run_ssh', 'sync', 'deploy', 'wait_ssh', 'chk_cloud_init',
           'chk_docker', 'load_pub_keys']

# %% ../nbs/03_vps.ipynb #8795cffa
import os, json, subprocess, time
from fastcore.all import L, Path, run, listify, timed_cache
from fastcloudinit.core import cloud_init_base, cloud_init_config, user, runcmd, reboot
from .core import Cli, mk_flags
from hcloud import Client
from hcloud.images import Image
from hcloud.server_types import ServerType
from hcloud.locations import Location
from hcloud.ssh_keys import SSHKey

# %% ../nbs/03_vps.ipynb #67f2b54ac2a375f9
class Multipass(Cli):
    'Wrap multipass CLI: manage local Ubuntu VMs for testing'
    def _run(self, cmd, *args): return run('multipass', cmd, *args)
    def launch(self, name, image='24.04', cpus=1, memory='1G', disk='10G', cloud_init:Path=None, mounts=None):
        'Launch a VM. cloud_init can be a YAML string or a file path.'
        args = mk_flags(image=image, cpus=cpus, memory=memory, disk=disk, sym=' ')
        if cloud_init and Path(cloud_init).is_file(): args += mk_flags(cloud_init=str(cloud_init), sym=' ')
        for hp, vp in (mounts or {}).items(): args += mk_flags(mount=f'{hp}:{vp}', sym=' ')
        self('launch', name, *args)
        return name

    def vms(self, running=False):
        'List VM names. running=True filters to Running state.'
        lst = L(json.loads(self('list', '--format', 'json')).get('list', []))
        if running: lst = lst.filter(lambda v: v.get('state') == 'Running')
        return list(lst.itemgot('name'))

    def ip(self, name) -> str:
        'Get IPv4 address of a VM.'
        return json.loads(self('info', name, '--format', 'json'))['info'][name]['ipv4'][0]

    def exec_(self, name, *cmd) -> str:
        'Run a command in a VM.'
        return self('exec', name, '--', *cmd)

    def rm(self, name, purge=True) -> None:
        'Delete a VM.'
        self('delete', name)
        if purge: self('purge')

    def transfer(self, src, dst) -> None:
        'Transfer files to/from a VM. Use "vmname:/path" for VM paths.'
        self('transfer', src, dst)

mp = Multipass()

def deploy_mp(name, src, path='/srv/app', build=True) -> str:
    'Sync local directory into a Multipass VM and run docker compose up -d.'
    mp.exec_(name, 'mkdir', '-p', path)
    mp.transfer(str(src).rstrip('/') + '/', f'{name}:{path}')
    cmd = ['docker', 'compose', '-f', f'{path}/docker-compose.yml', 'up', '-d', '--remove-orphans']
    if build: cmd.append('--build')
    return mp.exec_(name, *cmd)

# %% ../nbs/03_vps.ipynb #d9b26e5a
dock_cmd = [
    'curl -fsSL https://get.docker.com | sh',
    'usermod -aG docker {username}',
    'systemctl enable --now docker',
]

def vps_init(hostname, pub_keys, username='deploy', docker=True, pkgs=None, cmds=None, **kw):
    'Cloud-init YAML for a fresh VPS: user, UFW, optional Docker'
    rcmds = list(cmds or [])
    if docker: rcmds = [c.format(username=username) for c in dock_cmd] + rcmds
    default_pkgs = ['curl', 'fail2ban', 'unattended-upgrades']
    return cloud_init_config(hostname=hostname, username=username, pub_keys=pub_keys,
        packages=default_pkgs + list(pkgs or []), cmds=rcmds, **kw)

# %% ../nbs/03_vps.ipynb #bqtzq0gu82l
def multi_init(hostname, pub_keys, username='deploy', docker=True, pkgs=None, cmds=None):
    'Cloud-init for Multipass local VMs: no UFW, no hardening, optional Docker'
    rcmds = list(cmds or [])
    if docker: rcmds = [c.format(username=username) for c in dock_cmd] + rcmds
    return cloud_init_base(
        hostname,
        packages=['curl'] + list(pkgs or []),
        users=[user(username, pub_keys)],
        **runcmd(rcmds),
        **reboot(),
    )

# %% ../nbs/03_vps.ipynb #a2e72839
@timed_cache(300)
def hetz():
    token = os.environ.get('HCLOUD_TOKEN')
    if not token: raise ValueError('HCLOUD_TOKEN environment variable not set')
    return Client(token=token)

# %% ../nbs/03_vps.ipynb #238bbc63
def create(name, image='ubuntu-24.04', server_type='cx23', location=None, cloud_init=None, ssh_keys=None):
    'Create a Hetzner server. Returns IP.'
    resp = hetz().servers.create(
        name=name,
        server_type=ServerType(name=server_type),
        image=Image(name=image),
        location=Location(name=location) if location else None,
        user_data=cloud_init,
        ssh_keys=[SSHKey(name=k) for k in (ssh_keys or [])],
    )
    return {resp.server.public_net.ipv4.ip:resp}

def servers():
    'List Hetzner servers as [{name, ip, status}]'
    return L(hetz().servers.get_all()).map(lambda s: dict(name=s.name,ip=s.public_net.ipv4.ip,status=s.status))

def server_ip(name) -> str:
    'Get public IPv4 of a Hetzner server by name'
    s = hetz().servers.get_by_name(name)
    if not s: raise ValueError(f'Server {name!r} not found')
    return s.public_net.ipv4.ip

def delete(name):
    'Delete a Hetzner server by name'
    s = hetz().servers.get_by_name(name)
    if s: s.delete()

# %% ../nbs/03_vps.ipynb #1qtgnenon3p
def hetz_keys() -> list:
    'List SSH keys registered in the Hetzner account as [{name, fingerprint}].'
    return L(hetz().ssh_keys.get_all()).map(lambda k: dict(name=k.name, fingerprint=k.fingerprint))

def hetz_key_names() -> list:
    'Return SSH key name strings for use in provision(ssh_keys=[...]).'
    return [k['name'] for k in hetz_keys()]

# %% ../nbs/03_vps.ipynb #0f2c0407
def _ssh_base(host, user, key, port):
    a = ['ssh', '-o', 'StrictHostKeyChecking=accept-new']
    if key: a += ['-i', str(key)]
    if port != 22: a += ['-p', str(port)]
    return a + [f'{user}@{host}']

def run_ssh(host, *cmds, user='deploy', key=None, port=22, capture=False, check=True):
    'Run commands on remote host via SSH. capture=True returns stdout string.'
    r = subprocess.run(_ssh_base(host, user, key, port) + [' && '.join(cmds)],
                       capture_output=capture, text=capture, check=check)
    return r.stdout if capture else r

def sync(src, dst_path, host, user='deploy', key=None, port=22, exclude=None):
    'Rsync local path to remote host:dst_path. exclude: list of patterns for --exclude.'
    a = ['rsync', '-az', '--delete'] + (['-e', f'ssh -i {key}'] if key else [])
    for e in listify(exclude): a += ['--exclude', e]
    subprocess.run(a + [str(src), f'{user}@{host}:{dst_path}'], check=True)

def deploy(src, host, user='deploy', key=None, path='/srv/app', build=True, exclude=None):
    'Rsync local directory to remote host:path and run docker compose up -d.'
    run_ssh(host, f'mkdir -p {path}', user=user, key=key)
    sync(str(src).rstrip('/') + '/', path, host, user=user, key=key, exclude=exclude)
    cmd = f'cd {path} && docker compose up -d --remove-orphans' + (' --build' if build else '')
    return run_ssh(host, cmd, user=user, key=key)

# %% ../nbs/03_vps.ipynb #q4e3dvg4au
def wait_ssh(host, u='deploy', k=None, p=22, tout=120, interval=5):
    'Poll SSH until connection succeeds or raises TimeoutError.'
    dl = time.time() + tout
    while time.time() < dl:
        try: run_ssh(host, 'true', user=u, key=k, port=p); return True
        except Exception: time.sleep(interval)
    raise TimeoutError(f'SSH to {host} not ready after {tout}s')

def chk_cloud_init(host, u='deploy', k=None) -> str:
    'Return cloud-init status: done|running|error|unknown'
    try:
        o = run_ssh(host, 'sudo cloud-init status', user=u, key=k, capture=True)
        return o.split(': ', 1)[-1].strip() if ': ' in o else o.strip()
    except Exception: return 'unknown'

def chk_docker(host, u='deploy', k=None) -> bool:
    'Verify docker daemon is running and user can run containers.'
    try: run_ssh(host, 'docker info', user=u, key=k); return True
    except Exception: return False

# %% ../nbs/03_vps.ipynb #0929rkcanuri
def load_pub_keys(paths=None) -> list:
    'Load SSH public key strings. paths=None → auto-detect from ~/.ssh/id_*.pub'
    paths = paths or list(Path.home().glob('.ssh/id_*.pub'))
    return [Path(p).read_text().strip() for p in listify(paths) if Path(p).exists()]
